# Generated by Django 5.0.7 on 2024-08-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_condition',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
