# Generated by Django 5.0.7 on 2024-08-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalHistory', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('approved', 'approved')], max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalHistory.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.healthcareprovider')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
